### ISSUE TITLE
[BUG] ogbg-molfreesolv cannot be loaded in PR 255

### ISSUE THREAD

**Issue by StevenGolden1203** [Graph-Learning-Benchmarks/gli#263] opened 2022-08-31 02:04 UTC
Same error below happens for `ogbg-molpcba`

**To Reproduce**
In pr 255,
```
import gli
gli.dataloading.get_gli_dataset("ogbg-molfreesolv", "GraphRegression")
```

Error message:
```
l/lib/python3.9/_collections_abc.py:763, in Mapping.get(self, key, default)
    761 'D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.'
    762 try:
--> 763     return self[key]
    764 except KeyError:
    765     return default

File ~/miniconda3/envs/dgl/lib/python3.9/site-packages/numpy/lib/npyio.py:243, in NpzFile.__getitem__(self, key)
    241 if magic == format.MAGIC_PREFIX:
    242     bytes = self.zip.open(key)
--> 243     return format.read_array(bytes,
    244                              allow_pickle=self.allow_pickle,
    245                              pickle_kwargs=self.pickle_kwargs)
    246 else:
    247     return self.zip.read(key)

File ~/miniconda3/envs/dgl/lib/python3.9/site-packages/numpy/lib/format.py:747, in read_array(fp, allow_pickle, pickle_kwargs)
    745     pickle_kwargs = {}
    746 try:
--> 747     array = pickle.load(fp, **pickle_kwargs)
    748 except UnicodeError as err:
    749     # Friendlier error message
    750     raise UnicodeError("Unpickling a python object failed: %r\n"
    751                        "You may need to pass the encoding= option "
    752                        "to numpy.load" % (err,)) from err

ModuleNotFoundError: No module named 'scipy.sparse._lil'
```

**Comment by jiaqima** [comment] 2022-08-31 18:21
Duplicate of #258. Closing this issue.

**Closed by jiaqima** 2022-08-31 18:21 UTC
Labels: bug
